trainer:
  precision: '32-true' #'16-mixed'
  devices: [0]
  max_epochs: -1
  max_steps: 5000
  check_val_every_n_epoch: 5
  log_every_n_steps: 6
  callbacks:
    - class_path: "pytorch_lightning.callbacks.ModelCheckpoint"
      init_args:
        monitor: "error/val"
        mode: "min"
        filename: "best"
        save_last: true
model:
  class_path: model.heatmap_models.HeatMapUNet
  init_args:
    in_channel: 1
    n_kpts: 6
    channels:
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    blob_sigma: 11
    mse_scaling: 59
data:
  class_path: dataset.us_hip_dataset.USHipDataModule
  init_args:
    fold_idx: 0
    batch_size: 16
    use_data_aug: true