# pytorch_lightning==2.5.6
trainer:
  devices:
    - 0
  precision: 32-true
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      save_last: true
      monitor: "F1/val"
      mode: "max"
      filename: "best"
  max_epochs: -1
  max_steps: 30000
  val_check_interval: 100.0
model:
  class_path: model.line_seg_models.LineUNet
  init_args:
    pos_weight: 1
    channels:
    - 32
    - 64
    - 128
    - 256
    in_channel: 3
    out_channel: 1
data:
  class_path: dataset.line_dataset.LineDataModule
  init_args:
    batch_size: 32
    img_h: 64
    img_w: 64
    margin: -5
    bg_clr: 0.5
